CREATE TABLE IF NOT EXISTS `cmf_invite_click` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `click_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'click id',
  `ref_code` varchar(64) NOT NULL DEFAULT '' COMMENT 'invite code',
  `inviter_uid` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'inviter uid',
  `platform` varchar(20) NOT NULL DEFAULT '' COMMENT 'web platform',
  `ip` varchar(45) NOT NULL DEFAULT '' COMMENT 'client ip',
  `ip_hash` char(40) NOT NULL DEFAULT '' COMMENT 'sha1 ip',
  `user_agent` varchar(512) NOT NULL DEFAULT '' COMMENT 'user agent',
  `ua_hash` char(40) NOT NULL DEFAULT '' COMMENT 'sha1 user agent',
  `device_fingerprint` varchar(128) NOT NULL DEFAULT '' COMMENT 'app or browser fingerprint',
  `referer` varchar(512) NOT NULL DEFAULT '' COMMENT 'referer',
  `landing_url` varchar(512) NOT NULL DEFAULT '' COMMENT 'landing url',
  `download_url` varchar(512) NOT NULL DEFAULT '' COMMENT 'download url',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '0 clicked,1 matched,2 bound,3 expired',
  `matched_uid` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'invitee uid',
  `created_at` int NOT NULL DEFAULT '0',
  `updated_at` int NOT NULL DEFAULT '0',
  `expires_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_click_id` (`click_id`),
  KEY `idx_ref_code` (`ref_code`),
  KEY `idx_inviter_uid` (`inviter_uid`),
  KEY `idx_ip_hash_created` (`ip_hash`,`created_at`),
  KEY `idx_ua_hash_created` (`ua_hash`,`created_at`),
  KEY `idx_device_fingerprint` (`device_fingerprint`),
  KEY `idx_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='invite attribution clicks';

CREATE TABLE IF NOT EXISTS `cmf_invite_bind` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `invitee_uid` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'new user uid',
  `inviter_uid` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'inviter uid',
  `ref_code` varchar(64) NOT NULL DEFAULT '' COMMENT 'invite code',
  `click_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'click id',
  `match_method` varchar(32) NOT NULL DEFAULT '' COMMENT 'match method',
  `confidence` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '0-100',
  `device_fingerprint` varchar(128) NOT NULL DEFAULT '' COMMENT 'app device fingerprint',
  `ip` varchar(45) NOT NULL DEFAULT '' COMMENT 'bind ip',
  `ua_hash` char(40) NOT NULL DEFAULT '' COMMENT 'sha1 user agent',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '0 pending,1 bound,2 failed,3 already bound',
  `bind_result_code` int NOT NULL DEFAULT '0' COMMENT 'User.setDistribut result',
  `bind_result_msg` varchar(255) NOT NULL DEFAULT '' COMMENT 'bind result message',
  `created_at` int NOT NULL DEFAULT '0',
  `updated_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_invitee_uid` (`invitee_uid`),
  KEY `idx_inviter_uid` (`inviter_uid`),
  KEY `idx_ref_code` (`ref_code`),
  KEY `idx_click_id` (`click_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='invite attribution bindings';
