CREATE TABLE IF NOT EXISTS `cmf_live_source_room_pool` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `provider` varchar(32) NOT NULL DEFAULT 'douyin' COMMENT '授权来源平台',
  `room_id` varchar(128) NOT NULL DEFAULT '' COMMENT '平台房间号',
  `room_page` varchar(1000) NOT NULL DEFAULT '' COMMENT '直播间页面',
  `nickname` varchar(255) NOT NULL DEFAULT '' COMMENT '主播昵称',
  `uniq_id` varchar(255) NOT NULL DEFAULT '' COMMENT '平台主播唯一标识',
  `title` varchar(500) NOT NULL DEFAULT '' COMMENT '直播标题',
  `category_page` varchar(1000) NOT NULL DEFAULT '' COMMENT '来源分类页',
  `avatar` varchar(1000) NOT NULL DEFAULT '' COMMENT '头像',
  `cover` varchar(1000) NOT NULL DEFAULT '' COMMENT '封面',
  `gender_tag` varchar(32) NOT NULL DEFAULT 'unknown' COMMENT 'female/male/unknown',
  `verify_status` tinyint NOT NULL DEFAULT '0' COMMENT '0待审核 1通过 2拒绝',
  `verify_source` varchar(32) NOT NULL DEFAULT '' COMMENT 'manual/platform',
  `confidence` decimal(5,4) NOT NULL DEFAULT '0.0000',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1启用 0停用',
  `last_seen_at` int unsigned NOT NULL DEFAULT '0',
  `last_verified_at` int unsigned NOT NULL DEFAULT '0',
  `create_time` int unsigned NOT NULL DEFAULT '0',
  `update_time` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_provider_room` (`provider`,`room_id`),
  KEY `idx_pick` (`provider`,`gender_tag`,`verify_status`,`status`,`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='授权拉流房间池';
